-- Add all missing columns to stores table
ALTER TABLE stores ADD COLUMN custom_domain_request TEXT;
ALTER TABLE stores ADD COLUMN custom_domain_status TEXT DEFAULT 'none';
ALTER TABLE stores ADD COLUMN custom_domain_requested_at INTEGER;
ALTER TABLE stores ADD COLUMN cloudflare_hostname_id TEXT;
ALTER TABLE stores ADD COLUMN ssl_status TEXT DEFAULT 'pending';
ALTER TABLE stores ADD COLUMN dns_verified INTEGER DEFAULT 0;
ALTER TABLE stores ADD COLUMN subscription_status TEXT DEFAULT 'active';
ALTER TABLE stores ADD COLUMN usage_limits TEXT;
ALTER TABLE stores ADD COLUMN onboarding_status TEXT DEFAULT 'pending_plan';
ALTER TABLE stores ADD COLUMN setup_step INTEGER DEFAULT 0;
ALTER TABLE stores ADD COLUMN featured_product_id INTEGER;
ALTER TABLE stores ADD COLUMN landing_config TEXT;
ALTER TABLE stores ADD COLUMN theme_config TEXT;
ALTER TABLE stores ADD COLUMN business_info TEXT;
ALTER TABLE stores ADD COLUMN favicon TEXT;
ALTER TABLE stores ADD COLUMN social_links TEXT;
ALTER TABLE stores ADD COLUMN font_family TEXT DEFAULT 'inter';
ALTER TABLE stores ADD COLUMN footer_config TEXT;
ALTER TABLE stores ADD COLUMN custom_privacy_policy TEXT;
ALTER TABLE stores ADD COLUMN custom_terms_of_service TEXT;
ALTER TABLE stores ADD COLUMN custom_refund_policy TEXT;
ALTER TABLE stores ADD COLUMN notification_email TEXT;
ALTER TABLE stores ADD COLUMN email_notifications_enabled INTEGER DEFAULT 1;
ALTER TABLE stores ADD COLUMN low_stock_threshold INTEGER DEFAULT 10;
ALTER TABLE stores ADD COLUMN shipping_config TEXT;
ALTER TABLE stores ADD COLUMN facebook_pixel_id TEXT;
ALTER TABLE stores ADD COLUMN courier_settings TEXT;
ALTER TABLE stores ADD COLUMN is_customer_ai_enabled INTEGER DEFAULT 0;
ALTER TABLE stores ADD COLUMN ai_bot_persona TEXT;
ALTER TABLE stores ADD COLUMN default_language TEXT DEFAULT 'en';