/**
 * Lead Gen Session Transfer Route
 *
 * Route: /lead-gen/auth/session-transfer
 *
 * Completes cross-domain authentication for lead-gen customers.
 * Consumes a signed token generated by the main domain callback
 * and establishes a session on the lead-gen domain.
 */

import { LoaderFunctionArgs, redirect } from '@remix-run/cloudflare';
import { createCustomerSession, validateTransferToken } from '~/services/customer-auth.server';
import { resolveStore } from '~/lib/store.server';

function sanitizeRedirectPath(path: string | null, fallback = '/lead-dashboard'): string {
  if (!path) return fallback;
  if (!path.startsWith('/')) return fallback;
  if (path.startsWith('//')) return fallback;
  if (path.includes('\n') || path.includes('\r')) return fallback;
  return path;
}

export async function loader({ request, context }: LoaderFunctionArgs) {
  const url = new URL(request.url);
  const token = url.searchParams.get('token');
  const redirectTo = sanitizeRedirectPath(url.searchParams.get('redirectTo'), '/lead-dashboard');
  const env = context.cloudflare.env;
  const tenantStoreContext = await resolveStore(context, request);

  if (!token) {
    console.error('[LeadGenSessionTransfer] Missing token');
    return redirect('/lead-gen/auth/login?error=invalid_transfer');
  }

  const result = await validateTransferToken(token, env);

  if (!result) {
    console.error('[LeadGenSessionTransfer] Invalid or expired token');
    return redirect('/lead-gen/auth/login?error=expired_transfer');
  }

  const { customerId, storeId } = result;

  if (!tenantStoreContext || tenantStoreContext.storeId !== storeId) {
    console.error('[LeadGenSessionTransfer] Tenant mismatch', {
      tokenStoreId: storeId,
      tenantStoreId: tenantStoreContext?.storeId,
    });
    return redirect('/lead-gen/auth/login?error=invalid_transfer_store');
  }

  console.warn(`[LeadGenSessionTransfer] Successfully verified token for customer ${customerId}, store ${storeId}`);

  return createCustomerSession(customerId, storeId, redirectTo, env);
}

export default function LeadGenSessionTransfer() {}
