/**
 * Session Transfer Route
 * 
 * Route: /store/auth/session-transfer
 * 
 * Completes the cross-domain authentication flow.
 * Consumes a signed token generated by the main domain callback
 * and establishes a session on the custom domain.
 */

import { LoaderFunctionArgs, redirect } from 'react-router';
import { createCustomerSession, validateTransferToken } from '~/services/customer-auth.server';
import { resolveStore } from '~/lib/store.server';

function sanitizeRedirectPath(path: string | null, fallback = '/account'): string {
  if (!path) return fallback;
  if (!path.startsWith('/')) return fallback;
  if (path.startsWith('//')) return fallback;
  if (path.includes('\n') || path.includes('\r')) return fallback;
  return path;
}

export async function loader({ request, context }: LoaderFunctionArgs) {
  const url = new URL(request.url);
  const token = url.searchParams.get('token');
  const redirectTo = sanitizeRedirectPath(url.searchParams.get('redirectTo'), '/account');
  const env = context.cloudflare.env;
  const tenantStoreContext = await resolveStore(context, request);

  if (!token) {
    console.error('[SessionTransfer] Missing token');
    return redirect('/store/auth/login?error=invalid_transfer');
  }

  // Validate the token
  const result = await validateTransferToken(token, env);

  if (!result) {
    console.error('[SessionTransfer] Invalid or expired token');
    return redirect('/store/auth/login?error=expired_transfer');
  }

  const { customerId, storeId } = result;

  // Multi-tenant guard: transfer token storeId must match the current domain's store context.
  if (!tenantStoreContext || tenantStoreContext.storeId !== storeId) {
    console.error('[SessionTransfer] Tenant mismatch', {
      tokenStoreId: storeId,
      tenantStoreId: tenantStoreContext?.storeId,
    });
    return redirect('/store/auth/login?error=invalid_transfer_store');
  }

  console.warn(`[SessionTransfer] Successfully verified token for customer ${customerId}, store ${storeId}`);

  // Create session on THIS domain (the custom domain)
  return createCustomerSession(customerId, storeId, redirectTo, env);
}


export default function() {}
