/**
 * Session Transfer Route
 * 
 * Route: /store/auth/session-transfer
 * 
 * Completes the cross-domain authentication flow.
 * Consumes a signed token generated by the main domain callback
 * and establishes a session on the custom domain.
 */

import { LoaderFunctionArgs, redirect } from '@remix-run/cloudflare';
import { createCustomerSession, validateTransferToken } from '~/services/customer-auth.server';

export async function loader({ request, context }: LoaderFunctionArgs) {
  const url = new URL(request.url);
  const token = url.searchParams.get('token');
  const redirectTo = url.searchParams.get('redirectTo') || '/account';
  const env = context.cloudflare.env;

  if (!token) {
    console.error('[SessionTransfer] Missing token');
    return redirect('/store/auth/login?error=invalid_transfer');
  }

  // Validate the token
  const result = await validateTransferToken(token, env);

  if (!result) {
    console.error('[SessionTransfer] Invalid or expired token');
    return redirect('/store/auth/login?error=expired_transfer');
  }

  const { customerId, storeId } = result;

  console.warn(`[SessionTransfer] Successfully verified token for customer ${customerId}, store ${storeId}`);

  // Create session on THIS domain (the custom domain)
  return createCustomerSession(customerId, storeId, redirectTo, env);
}
