/**
 * Published Custom Page Route
 * 
 * Renders the HTML and CSS generated by the GrapesJS editor.
 */

import { json, type LoaderFunctionArgs, type MetaFunction } from '@remix-run/cloudflare';
import { useLoaderData } from '@remix-run/react';
import { drizzle } from 'drizzle-orm/d1';
import { eq, and } from 'drizzle-orm';
import { landingPages } from '@db/schema';
import { useTrackVisit } from '~/hooks/use-track-visit';

export const meta: MetaFunction<typeof loader> = ({ data }) => {
  if (!data || 'error' in data) {
    return [{ title: 'Page Not Found' }];
  }
  return [{ title: data.name }];
};

export async function loader({ params, context }: LoaderFunctionArgs) {
  const { slug } = params;
  const storeId = context.storeId;

  if (!storeId) {
    throw new Response('Store not found', { status: 404 });
  }

  if (!slug) {
    throw new Response('Slug required', { status: 400 });
  }

  const db = drizzle(context.cloudflare.env.DB);
  const result = await db
    .select()
    .from(landingPages)
    .where(
      and(
        eq(landingPages.slug, slug),
        eq(landingPages.storeId, storeId as number),
        eq(landingPages.isPublished, true)
      )
    )
    .limit(1);

  if (result.length === 0) {
    throw new Response('Page not found or not published', { status: 404 });
  }

  return json(result[0]);
}

export default function PublishedPageRoute() {
  const page = useLoaderData<typeof loader>();
  
  // Track visitor
  useTrackVisit(page.storeId);

  return (
    <>
      {/* External CSS Dependencies - Load FIRST */}
      {/* Using Tailwind Play CDN for full color palette support */}
      <script src="https://cdn.tailwindcss.com"></script>
      <script dangerouslySetInnerHTML={{ __html: `
        tailwind.config = {
          theme: {
            extend: {
              colors: {
                emerald: { 50: '#ecfdf5', 100: '#d1fae5', 200: '#a7f3d0', 300: '#6ee7b7', 400: '#34d399', 500: '#10b981', 600: '#059669', 700: '#047857', 800: '#065f46', 900: '#064e3b' },
              }
            }
          }
        }
      `}} />
      <link href="https://fonts.googleapis.com/css2?family=Hind+Siliguri:wght@300;400;500;600;700&display=swap" rel="stylesheet" />
      
      {/* Base styles for published pages */}
      <style dangerouslySetInnerHTML={{ __html: `
        .published-page-root { font-family: 'Hind Siliguri', sans-serif; }
        .published-page-root * { box-sizing: border-box; }
      `}} />

      {/* Inject custom CSS from GrapesJS AFTER Tailwind */}
      <style dangerouslySetInnerHTML={{ __html: page.cssContent || '' }} />
      
      {/* Render HTML Content */}
      <div 
        className="published-page-root"
        dangerouslySetInnerHTML={{ __html: page.htmlContent || '' }} 
      />
    </>
  );
}
