/**
 * Published Custom Page Route
 * 
 * Renders the HTML and CSS generated by the GrapesJS editor.
 */

import { json, type LoaderFunctionArgs, type MetaFunction } from '@remix-run/cloudflare';
import { useLoaderData } from '@remix-run/react';
import { drizzle } from 'drizzle-orm/d1';
import { eq, and } from 'drizzle-orm';
import { landingPages } from '@db/schema';
import { useTrackVisit } from '~/hooks/use-track-visit';

export const meta: MetaFunction<typeof loader> = ({ data }) => {
  if (!data || 'error' in data) {
    return [{ title: 'Page Not Found' }];
  }
  return [{ title: data.name }];
};

export async function loader({ params, context }: LoaderFunctionArgs) {
  const { slug } = params;
  const storeId = context.storeId;

  if (!storeId) {
    throw new Response('Store not found', { status: 404 });
  }

  if (!slug) {
    throw new Response('Slug required', { status: 400 });
  }

  const db = drizzle(context.cloudflare.env.DB);
  const result = await db
    .select()
    .from(landingPages)
    .where(
      and(
        eq(landingPages.slug, slug),
        eq(landingPages.storeId, storeId as number),
        eq(landingPages.isPublished, true)
      )
    )
    .limit(1);

  if (result.length === 0) {
    throw new Response('Page not found or not published', { status: 404 });
  }

  return json(result[0]);
}

export default function PublishedPageRoute() {
  const page = useLoaderData<typeof loader>();
  
  // Track visitor
  useTrackVisit(page.storeId);

  return (
    <>
      {/* Inject custom CSS */}
      <style dangerouslySetInnerHTML={{ __html: page.cssContent || '' }} />
      
      {/* External CSS Dependencies (like Tailwind if used in canvas) */}
      <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css" />
      <link href="https://fonts.googleapis.com/css2?family=Hind+Siliguri:wght@300;400;500;600;700&display=swap" rel="stylesheet" />

      {/* Render HTML Content */}
      <div 
        className="published-page-root"
        dangerouslySetInnerHTML={{ __html: page.htmlContent || '' }} 
      />
    </>
  );
}
