/**
 * Cloudflare Worker Entry Point for Remix SSR
 * 
 * This file handles incoming requests and routes them through Remix.
 * Static assets are served via the ASSETS binding.
 */

import { createRequestHandler } from "@remix-run/cloudflare";

// @ts-expect-error - the server build file is generated by `remix vite:build`
import * as build from "./build/server/index.js";

interface Env {
  ASSETS: Fetcher;
  DB: D1Database;
  R2: R2Bucket;
  STORE_CACHE: KVNamespace;
  SESSION_SECRET?: string;
  SAAS_DOMAIN?: string;
  R2_PUBLIC_URL?: string;
  MAIN_APP_URL?: string;
  SUPER_ADMIN_EMAIL?: string;
}

const requestHandler = createRequestHandler(build, "production");

export default {
  async fetch(request: Request, env: Env, ctx: ExecutionContext): Promise<Response> {
    try {
      // Create load context with Cloudflare bindings
      const loadContext = {
        cloudflare: {
          env,
          ctx,
          cf: request.cf,
        },
      };
      
      return await requestHandler(request, loadContext);
    } catch (error) {
      console.error("Worker error:", error);
      return new Response("Internal Server Error", { status: 500 });
    }
  },
};
