/**
 * Cloudflare Pages Function Handler for Remix SSR
 * 
 * This file handles all incoming requests and routes them through Remix.
 * Required for Pages Functions to work with Remix v2.
 */

import { createPagesFunctionHandler } from "@remix-run/cloudflare-pages";

// @ts-expect-error - the server build file is generated by `remix vite:build`
import * as build from "../build/server";

export const onRequest = createPagesFunctionHandler({
  build,
  getLoadContext: (context) => ({
    cloudflare: context,
  }),
});
